version: "2"

services:
  mobile_api:
    container_name: mobile_api
    build: .
    ports: 
      - 127.0.0.1:5001:5000
    networks:
      mobileapi:
        aliases:
          - mobileapi
networks:
  mobileapi:
    driver: host