version: "2"

services:
  mobile_api:
    container_name: mobile_api
    build: .
    ports: 
      - 5001:5000
    networks:
      - mobileapi
    external_links:
      - mobileapi

networks:
  mobileapi:
    driver: bridge