version: "2"

services:
  app:
    image: golang:latest
    volumes:
      - .:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    port: 
      - 5001:5000
    command: >
     go build main.go 
     && ./main
