version: "3"

services:
  mobile_api:
    container_name: mobile_api
    build: .
    ports: 
      - 5001:5000
    networks:
      mobileapi:
        aliases:
          - mobileapi
networks:
  mobileapi:
    ipv4_address: 10.5.0.6