version: "2"

services:
  mobile_api:
    container_name: mobile_api
    build: .
    ports: 
      - 5001:5000
    networks:
      mobileapi:
        aliases:
          - mobileapi
networks:
  mobileapi:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
    